name: PR Checks

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  pr-checks:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    name: PR Checks
    runs-on: ${{ matrix.os }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install extension
        shell: bash
        run: |
          gh extensions install .

      - name: Check automatically installs latest
        shell: bash
        run: |
          LATEST=`gh release list --repo github/codeql-cli-binaries -L 1 | cut -f 3`

          # Note we need to run a command before trying to parse the output below, or the
          # messages from the download will end up in the JSON that jq tries to parse
          gh codeql version 

          INSTALLED=`gh codeql version --format json | jq -r '.version'`
          if [[ "v$INSTALLED" != $LATEST ]]; then
            echo "::error::Expected latest version of $LATEST to be installed, but found v$INSTALLED"
            exit 1
          fi

      - name: Check basic functionality
        working-directory: test-resources
        shell: bash
        run: |
          gh codeql set-version 2.6.1
          gh codeql database create -l cpp -s test-repo -c "gcc -o main main.c" test-db
          gh codeql pack install test-pack
          gh codeql database analyze --format=sarif-latest --output=out.sarif test-db test-pack/allExpressions.ql
          RESULTS=`jq '.runs[0].results | length' out.sarif`
          if [[ $RESULTS != 1 ]]; then
            echo "::error::Invalid number of results from test query, expected 1 but got $RESULTS"
            exit 1
          fi

      - name: Check version pinning
        shell: bash
        run: |
          # Set the version without a v prefix
          gh codeql set-version 2.5.9
          VERSION=`gh codeql version --format json | jq -r '.version'`
          if [[ $VERSION != "2.5.9" ]]; then
            echo "::error::Expected version 2.5.9 but got $VERSION"
            exit 1
          fi
          gh codeql list-installed | grep v2.5.9

          # Set the version with a v prefix
          COUNT_BEFORE=`gh codeql list-installed | wc -l`
          gh codeql set-version v2.5.9
          COUNT_AFTER=`gh codeql list-installed | wc -l`
          if [[ $COUNT_BEFORE != $COUNT_BEFORE ]]; then
            echo "::error::Installing an already installed version changed the number of installed versions from $COUNT_BEFORE to $COUNT_AFTER!"
            exit 1
          fi

      - name: Check version unpinning
        shell: bash
        run: |
          gh codeql set-version latest
          VERSION=`gh codeql version --format json | jq -r '.version'`
          if [[ $VERSION == "2.5.9" ]]; then
            echo "::error::Expected latest version but got 2.5.9"
            exit 1
          fi

      - name: Check local version pinning
        shell: bash
        run: |
          # Enable local version support
          gh codeql local-version on
          gh codeql set-version latest
          # Get the latest installed version
          LATEST=`gh codeql version --format json | jq -r '.version'`
          # Set a local version
          gh codeql set-local-version 2.5.9
          VERSION=`gh codeql version --format json | jq -r '.version'`
          if [[ $VERSION != "2.5.9" ]]; then
            echo "::error::Expected version 2.5.9 but got $VERSION"
            exit 1
          fi

          # Create a temp directory so we can  change the working directory
          mkdir temp
          pushd temp
          OTHER_VERSION=`gh codeql version --format json | jq -r '.version'`

          if [[ $OTHER_VERSION != $LATEST ]]; then
            echo "::error::Expected version $LATEST but got $OTHER_VERSION"
            exit 1
          fi
          popd
          rmdir temp
          gh codeql unset-local-version
          # Disable local version support
          gh codeql local-version off

      - name: Check local version unpinning
        shell: bash
        run: |
          # Enable local version support
          gh codeql local-version on
          gh codeql set-version latest
          # Get the latest installed version
          LATEST=`gh codeql version --format json | jq -r '.version'`
          # Set a local version
          gh codeql set-local-version 2.5.9
          # Unset the local version
          gh codeql unset-local-version
          if [[ $VERSION == "2.5.9" ]]; then
            echo "::error::Expected $LATEST version but got 2.5.9"
            exit 1
          fi
          # Disable local version support
          gh codeql local-version off

      - name: Check local version pinning modification
        shell: bash
        run: |
          # Enable local version support
          gh codeql local-version on
          gh codeql set-version latest
          # Get the latest installed version
          LATEST=`gh codeql version --format json | jq -r '.version'`
          # Set a local version
          gh codeql set-local-version 2.5.9
          VERSION=`gh codeql version --format json | jq -r '.version'`
          if [[ $VERSION != "2.5.9" ]]; then
            echo "::error::Expected version 2.5.9 but got $VERSION"
            exit 1
          fi

          # Modify the pinned version without using the CLI
          echo v2.7.6 > .codeql-version
          # We run the command twice to prevent cURL output from causing a `jq` parser error.
          gh codeql version
          VERSION=`gh codeql version --format json | jq -r '.version'`
          if [[ $VERSION != "2.7.6" ]]; then
            echo "::error::Expected version 2.7.6 but got $VERSION"
            exit 1
          fi
          gh codeql unset-local-version
          # Disable local version support
          gh codeql local-version off

      - name: Check local version pinning is disabled by default
        shell: bash
        run: |
          gh codeql set-version latest
          # Get the latest installed version
          LATEST=`gh codeql version --format json | jq -r '.version'`

          # Modify the pinned version without using the CLI
          echo v2.7.6 > .codeql-version
          # We run the command twice to prevent cURL output from causing a `jq` parser error.
          gh codeql version
          VERSION=`gh codeql version --format json | jq -r '.version'`
          if [[ $VERSION = "2.7.6" ]]; then
            echo "::error::Expected version $LATEST but got $VERSION"
            exit 1
          fi
          rm .codeql-version

      - name: Check getting nightly version
        shell: bash
        run: |
          gh codeql set-channel nightly
          gh codeql set-version codeql-bundle-20210831-manual
          VERSION=`gh codeql version --format json | jq -r '.version'`
          if [[ $VERSION != "2.6.0+202108311306" ]]; then
            echo "::error::Expected version 2.6.0+202108311306 but got $VERSION"
            exit 1
          fi
          gh codeql set-channel release

      - name: Check version override
        shell: bash
        run: |
          gh codeql set-version latest
          # We run the command with a version override twice such that first run will download the CodeQL CLI
          # and the cURL output doesn't confuse the `jq` parser in the second run.
          # This implicit download is to test that we properly support the implicit download of a requested version if it is not present.
          GH_CODEQL_VERSION=v2.7.6 gh codeql version
          VERSION=`GH_CODEQL_VERSION=v2.7.6 gh codeql version --format json | jq -r '.version'`

          if [[ $VERSION != "2.7.6" ]]; then
            echo "::error::Expected version 2.7.6 but got $VERSION"
            exit 1
          fi

      - name: Check use of stub
        shell: bash
        run: |
          gh codeql set-version latest
          VERSION=`gh codeql version --format json | jq -r '.version'`

          mkdir temp
          gh codeql install-stub temp
          OTHER_VERSION=`temp/codeql version --format json | jq -r '.version'`
          if [[ $OTHER_VERSION != $VERSION ]]; then
            echo "::error::Expected version $VERSION but got $OTHER_VERSION"
            exit 1
          fi

          rm -r temp
